name: Minecraft Server Setup

on:
  push:
    branches:
      - main

jobs:
  setup-minecraft-server:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Java
    - name: Install Java 17
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jre-headless

    # Step 3: Create Directory for Server
    - name: Create Minecraft Server Directory
      run: |
        mkdir -p minecraft-server
        ls -la # Debug: List directory contents

    # Step 4: Download Minecraft Server JAR
    - name: Download Minecraft Server JAR
      run: |
        cd minecraft-server
        curl -O https://launcher.mojang.com/v1/objects/45810d238246d90e811d896f87b14695b7fb6839/server.jar
        ls -la # Debug: Ensure file is downloaded
      continue-on-error: false

    # Step 5: Accept EULA
    - name: Create EULA File
      run: |
        echo "eula=true" > minecraft-server/eula.txt
        cat minecraft-server/eula.txt # Debug: Verify content

    # Step 6: Start Minecraft Server
    - name: Start Minecraft Server
      run: |
        cd minecraft-server
        java -Xmx1024M -Xms1024M -jar server.jar nogui
