name: Deploy Minecraft Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        ssh username@your-server-ip 'bash -s' < ./deploy.sh
