name: Minecraft Server Setup

on:
  push:
    branches:
      - main

jobs:
  setup-minecraft-server:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Java
    - name: Install Java 17
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jre-headless

    # Step 3: Download Minecraft Server JAR
    - name: Download Minecraft Server
      run: |
        mkdir minecraft-server
        cd minecraft-server
        https://piston-data.mojang.com/v1/objects/45810d238246d90e811d896f87b14695b7fb6839/server.jar


    # Step 4: Accept Minecraft EULA
    - name: Accept EULA
      run: |
        echo "eula=true" > minecraft-server/eula.txt

    # Step 5: Start Minecraft Server
    - name: Start Minecraft Server
      run: |
        cd minecraft-server
        java -Xmx1024M -Xms1024M -jar server.jar nogui
